version: '3.8'

services:
  # Edge Simulator
  edge_simulator:
    build:
      context: .
      dockerfile: edge_simulator.dockerfile
    container_name: mqtt_edge_simulator
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
      - iot_network
  
  # Backend Consumer
  backend_consumer:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: mqtt_backend_consumer
    env_file:
      - .env
    depends_on:
      - mosquitto
      - influxdb
      - mongodb
    restart: unless-stopped
    networks:
      - iot_network
  # MQTT Broker (Eclipse Mosquitto with MQTT v5 support)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "${MQTT_PORT}:1883"
      - "8444:8444"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - iot_network

  # InfluxDB v2
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    restart: unless-stopped
    networks:
      - iot_network

  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: unless-stopped
    networks:
      - iot_network

networks:
  iot_network:
    driver: bridge

volumes:
  influxdb_data:
  influxdb_config:
  mongodb_data:
  mongodb_config: